language: node_js
node_js:
- 11
jobs:
  include:
    - stage: prepare
      script: yarn build && yarn test:unit
    - stage: deploy
      before_install:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      script: "npm publish --access public dist/"
      on:
        tags: true
