language: node_js
node_js:
- 11
script: yarn build && yarn test:unit

before_deploy: cd dist
deploy:
  provider: npm
  email: "rumlo@vscht.cz"
  api_key:
    secure: "QMy/MgY5VT+UixDYusCump/skpK+YQWMUMdYLqwSNTnILPvM3kXe3WsfEb3jJKKR7VFubGAd01CFMWvThbPLEEGco/yw9sk6Gnv9u+6CHkQpu+0Gv5WtSrleb/k5p9SoEilECTz7SUr5NIpEMywa99FLzUZWmpeb6E506YGpphSZv+ppjKEkEtu4mg+TzuTRHpuJ/TBH4U/1u6RifqngruOQTmHl0jW8szhhpOBjSbvTTkYKuWMO0gc4IuZD3CL9U0QqgftCaxJVwgqAK+/TVaKitvJEU6IvAoL3RcqzMtK33Kq95nq8FcdH0C0CE0+QR+8L6267emHAf15R1pogu7y9elsjaEqfWvmhP4ewkvsFGPHk+/mBqpXUzUhnwgiurxXVld8IIPIpMlZ0IKUd9LQrVEHSHQwSlbu07wscKd6gWpI+jZNr9+Z4Ixo1K0m0B18KYr/KFYVAbNkYcaZdZgUPStjuLPiS25uSXBVQVr6kEQV1tAENxeBpwUKchGmxkalXZddr9UtZ0LjQ/9wNapQptgaKa1Q1C43i4Jux/zpA7qunfOV5mC1XRaLqGyoKkUSV3N+1GUSbcjy2HUpECklZ4dSM8dFf6mtJaigq5Uwd1oIG+MkZujLZbmOOstGlQcEWT7Rdz5VqhBPgOP0ldtY76ref01FAlp5C007zJSs="
  on:
    tags: true
after_deploy: cd ..
